language: python
install:
  - pip install -r flowthrone/python/requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - pytest --cov=flowthrone/python/
after_success:
  - coveralls

branches:
  only:
  - master
